### ISSUE TITLE
Content license of sponsor logos

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/seagl.github.io#266]
The website currently says:

> Unless otherwise specified, all website content is licensed [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/).

I expect that the [sponsor logos](https://seagl.org/sponsors/) aren’t compatibly licensed and need an exception. What should it say and where should it go?

**Comment by koronkowy** [comment]
I think you can comment after, "Logos provided by sponsors and other partners are used with permission on this site and not licensed by SeaGL." and then make sure proper use is defined in the sponsorship documentation (tell them exactly where, how, and what duration of use) and all due diligence is done to use logos in conjunction with the sponsor's style guides (no color or sizing manipulation or bad use like heavily rasterizing and pixelating logos).

This can be quite a bit of a nightmare because who you talk to to negotiate sponsorship isn't always keyed in or so much aware of the brand guidelines of the org they represent. I have historically liked to ask for the logo to be provided by the partner or if using one from a prior year to get confirmation with the contact that it is still the correct one to use vs. self sourcing on the web.
